version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  AfterInstall:
    - location: src/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: src/npm-start.sh
      runas: root
      timeout: 60