version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  pre-build:
    commands:
      - echo Run unit tests
      - npm test
  build:
    commands:
      - echo Build started on $(date +%Y-%m-%d--%H:%m:%S)
      - npm run build
  post_build:
    commands:
      - echo Build ended on $(date +%Y-%m-%d--%H:%m:%S)
artifacts:
  files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths