version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn test
  post_build:
    commands:
      - echo Build ended on `date`
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths