version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on $(date +%Y-%m-%d %H:%i%s) 
      - npm test
  post_build:
    commands:
      - echo Build ended on $(date +%Y-%m-%d %H:%i%s)
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths